version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - run:
          command: curl --request POST \ --url https://circleci.com/api/v2/project/gh/CircleCI-Public/api-preview-docs/pipeline \ --header 'authorization: Basic $CIRCLECI_AUTH_TOKEN' \ --header 'content-type: application/json' \ --data '{"branch":"feature/design-new-api","tag":"v3.1.4159","parameters":{"deploy_prod":true}}'
          name: Trigger CircleCI Pipeline via Curl
